### ISSUE TITLE
Ошибка при handleUpdate

### ISSUE THREAD

**Issue by zelenovsky** [gramiojs/gramio#3]
Привет! пробую запустить бота через  webhook со своим обработчиком
```
const data = await request.json();
bot.updates.handleUpdate(data);
```

но получаю такую ошибку
```
TypeError: undefined is not an object (evaluating 'this.info.username')
      at /Users/artemzelenov/Developer/TrainingBot/node_modules/gramio/dist/bot.js:706:44
      at some (:1:11)
      at /Users/artemzelenov/Developer/TrainingBot/node_modules/gramio/dist/bot.js:700:39
      at /Users/artemzelenov/Developer/TrainingBot/node_modules/gramio/dist/composer.js:23:30
      at /Users/artemzelenov/Developer/TrainingBot/node_modules/gramio/dist/composer.js:21:32
      at nextDispatch (/Users/artemzelenov/Developer/TrainingBot/node_modules/middleware-io/lib/index.js:52:40)
      at /Users/artemzelenov/Developer/TrainingBot/node_modules/middleware-io/lib/index.js:52:67
      at /Users/artemzelenov/Developer/TrainingBot/node_modules/middleware-io/lib/index.js:280:15
      at /Users/artemzelenov/Developer/TrainingBot/node_modules/middleware-io/lib/index.js:278:8
      at nextDispatch (/Users/artemzelenov/Developer/TrainingBot/node_modules/middleware-io/lib/index.js:52:40)
      at /Users/artemzelenov/Developer/TrainingBot/node_modules/middleware-io/lib/index.js:58:16
      at compose (/Users/artemzelenov/Developer/TrainingBot/node_modules/gramio/dist/composer.js:68:14)
      at /Users/artemzelenov/Developer/TrainingBot/node_modules/gramio/dist/updates.js:52:27
      at handleUpdate (/Users/artemzelenov/Developer/TrainingBot/node_modules/gramio/dist/updates.js:17:24)
```

Инициализация бота
```
const url = await ngrok.connect(5173);
await bot.api.setWebhook({ url });
await bot.init();
```

Текущий стек: bun, sveltekit

В чем может быть проблема?

**Comment by kravetsone** [comment]
Привет! Проблема решилась?

**Comment by zelenovsky** [comment]
> Привет! Проблема решилась?

Да, я не в том месте init() вызвал. Спасибо
